In [1]:
import torch

c:\Users\theav\SynologyDrive\Uni Bielefeld\Neuronale Netze in der Sprachverarbeitung\env\Lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


In [2]:
t1 = torch.tensor([1,2])

In [3]:
t1

tensor([1, 2])

In [4]:
t1 * 2

tensor([2, 4])

In [5]:
t1.size()

torch.Size([2])

In [6]:
mat1 = torch.tensor([[1,2],[5,6]])

In [7]:
mat1

tensor([[1, 2],
        [5, 6]])

In [8]:
mat1[1]

tensor([5, 6])

In [10]:
mat1[:,1]

tensor([2, 6])

In [11]:
mat3 = torch.tensor([[1,2,10,20],[5,6,50,60]])

In [12]:
mat3[0:2]

tensor([[ 1,  2, 10, 20],
        [ 5,  6, 50, 60]])

In [13]:
mat3[0:1]

tensor([[ 1,  2, 10, 20]])

In [14]:
mat3[0]

tensor([ 1,  2, 10, 20])

In [15]:
mat3[0:1].size()

torch.Size([1, 4])

In [16]:
mat3[0].size()

torch.Size([4])

In [37]:
corpus = [["Every dog loves a cat.", "Not every mouse loves a cat.", "All cats are happy.", "Not all dogs are happy."]]

In [18]:
bow = torch.zeros(4,4)

In [19]:
bow

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
bow[0:2]

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
bow[0,2]

tensor(0.)

In [22]:
bow[0,2] = 1

In [23]:
bow

tensor([[0., 0., 1., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
### TODO: befülle die BOW-Matrix so, dass jeder Text aus dem corpus 
### als Vektor über dem Vokabular (dog, cat, loves, happy) dargestellt wird

In [41]:
vocab = ["dog", "cat", "loves", "happy"]

for i, sentence in enumerate(corpus[0]):
    #remove the ending punctuation
    sentence = sentence.replace(".", "")
    
    #count the occurences of the words in the sentence
    word_counts = {}
    for word in sentence.split():
        if word in word_counts:
            word_counts[word] += 1
        else:
            word_counts[word] = 1
            
    #fill the BOW matrix
    for j, word in enumerate(vocab):
        if word in word_counts:
            bow[i, j] = word_counts[word]
            
print(bow)

tensor([[1., 1., 1., 0.],
        [0., 1., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]])
